platform:ios, '8.0'

install! 'cocoapods',
    :integrate_targets => false

pod 'Bugly'
pod 'RongCloudIM/IMLib','4.0.1'
#pod 'RongRTCLib','4.0.1'
#pod 'RongCloudRTC/RongCallLib','2.9.12'
#pod 'RongCloudRTC/RongCallKit','2.9.12'
#pod 'AFNetworking'
#pod 'PromiseKit','~>6.10.0'
target '' do
end
