platform:ios, '8.0'

install! 'cocoapods',
    :integrate_targets => false

pod 'Bugly'
pod 'RongCloudIM/IMLib','~>2.9.19'
#pod 'RongRTCLib','~>3.0.7'
pod 'RongCloudRTC/RongCallLib','2.9.12'
pod 'RongCloudRTC/RongCallKit','2.9.12'
pod 'AFNetworking'
pod 'PromiseKit','~>6.10.0'
target '' do
end
