# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYWebImageTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'YYWebImage'
  pod 'YYImage/WebP'
  # Pods for YYWebImageTest

  target 'YYWebImageTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YYWebImageTestUITests' do
    # Pods for testing
  end

end
