# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SDWebImageTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDWebImageTest
  pod 'SDWebImage'
  pod 'SDWebImageWebPCoder', :git => 'https://github.com/SDWebImage/SDWebImageWebPCoder.git', :branch => 'master'
  target 'SDWebImageTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDWebImageTestUITests' do
    # Pods for testing
  end

end
