# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDWebImageTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDWebImageTest
  pod 'SDWebImage', '5.18.12'
  target 'SDWebImageTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDWebImageTestUITests' do
    # Pods for testing
  end

end
